clear; clc; close all;

% SC Estimates
SC_mass = 2864; % kg, Estimated mass of HEIMDALL
Payload_power = 284; % W, power estimate of payload
A = 8*pi; % m^2, estimated cylindrical SC shape (1 m radius, 3 m height)
Ac = 2*pi; % m^2, equivalent sphere w/ same surface area as cylinder

AbS_coeff = 0.3; % Solar spectrum
EmmS_coeff = AbS_coeff; % SC treated as gray body

AbI_coeff = 0.9; % IR
EmmI_coeff = AbI_coeff; % SC treated as gray body 

sigma = 5.67e-8; % W/m^2K^4, Stefann-Boltzmann constant
epsilon = EmmI_coeff; % Emitted radiation using IR emmissivity
alpha = AbS_coeff;



% Solar Absorbed Energy q_solar
qs = 1362; % W/m^2, Solar flux at 1 Au
Gs_eq = qs;
Q_solareq = alpha * Gs_eq * Ac; % Direct solar absorption

QI = 0; % Earth IR (planet shine) zero due to far distance

QR = 0; % Earth albedo zero due to far distance

q_solar = Q_solareq + QI + QR; % W, Total absorbed energy


% Heat generated by SC due to power dissipation of components Qgen
Q_gen = Payload_power; % W, only power of payload included

% Steady state assumption stored power is zero
Q_stored = 0;

% Radiated out heat
Q_outrad = q_solar + Q_gen - Q_stored;

% Baseline equilibrium case
qs = 1362; % W/m^2, Solar flux at 1 Au
Gs_eq = qs;
Q_gen_eq = Payload_power;   % baseline internal heat
Q_solareq = alpha * Gs_eq * Ac; % Direct solar absorption

T_eq = ((Q_solareq + Q_gen_eq + QI + QR) / (epsilon * sigma * A))^(1/4);
T_eq_C = T_eq - 273.15;

fprintf('Equilibrium Temperature = %.2f K\n', T_eq);
fprintf('Equilibrium Temperature = %.2f C\n\n', T_eq_C);

% HOT CASE assumptions
Q_genhot = 650; % W, estimated full power
Gs_hot = 1418; 
Q_solar_hot = alpha * Gs_hot * Ac;

T_hot = ((Q_solar_hot + Q_genhot + QI + QR) / (epsilon * sigma * A))^(1/4);
T_hot_C = T_hot - 273.15;

fprintf('Worst Case Hot Estimate Temp = %.2f K\n', T_hot);
fprintf('Worst Case Hot Estimate Temp = %.2f C\n', T_hot_C);

% COLD CASE assumptions
Gs_cold = 1326;
T_cold = ((Q_gen + QI) / (epsilon * sigma * A))^(1/4);
T_cold_C = T_cold - 273.15;

fprintf('Worst Case Cold Estimate Temp = %.2f K\n', T_cold);
fprintf('Worst Case Cold Estimate Temp = %.2f C\n', T_cold_C);
